default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: db

development:
  <<: *default
  database: docker-test_development

test:
  <<: *default
  database: docker-test_test

production:
  <<: *default
  database: docker-test_production
  username: docker-test
  password: <%= ENV['DOCKER-TEST_DATABASE_PASSWORD'] %>
